# Generated by Django 4.2.4 on 2023-08-09 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
                ('sex', models.IntegerField()),
                ('address', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Hobbit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('hobbit_name', models.CharField(max_length=32)),
                ('who', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alice.person')),
            ],
        ),
    ]
