# Generated by Django 4.2.4 on 2023-08-20 01:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alice', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('jobName', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='PersonAndJob',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alice.job')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alice.person')),
            ],
        ),
    ]
