# Generated by Django 4.2.4 on 2023-08-20 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alice', '0002_job_personandjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='personandjob',
            name='salary',
            field=models.IntegerField(default=0),
        ),
    ]
