# Generated by Django 4.2.4 on 2023-09-03 02:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('alice', '0005_navigation_permission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navigation',
            name='permission',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.permission'),
        ),
    ]
