# Generated by Django 4.2.4 on 2023-09-03 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alice', '0006_alter_navigation_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='navigation',
            name='url',
            field=models.CharField(default=11, max_length=64, unique=True),
            preserve_default=False,
        ),
    ]
