# Generated by Django 4.2.4 on 2023-09-03 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alice', '0007_navigation_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
    ]
