# Generated by Django 4.2.4 on 2023-09-03 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alice', '0008_basemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='basemodel',
            name='contents',
            field=models.CharField(default=1, max_length=32),
            preserve_default=False,
        ),
    ]
