# Generated by Django 4.2.4 on 2023-09-03 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alice', '0010_delete_basemodel_remove_personandjob_job_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='navigation',
            old_name='url',
            new_name='path',
        ),
    ]
