# Generated by Django 4.2.4 on 2023-09-06 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alice', '0012_navigation_component'),
    ]

    operations = [
        migrations.CreateModel(
            name='Administrators',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('navigation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alice.navigation')),
            ],
        ),
    ]
