# Generated by Django 4.2.4 on 2023-09-06 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alice', '0013_administrators'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrators',
            name='name',
            field=models.IntegerField(),
        ),
    ]
